/**
 * esp32_camera_object_detection.ino
 *
 * Captures a frame from the OV2640 camera on an AI Thinker ESP32-CAM board,
 * runs a quantised MobileNetV1 image-classification model via TensorFlow Lite
 * for Microcontrollers, and prints the top predicted label with its confidence
 * score to the Serial console.
 *
 * Required Arduino libraries (install via Sketch → Include Library →
 * Manage Libraries…):
 *   • TensorFlowLite_ESP32  ≥ 0.9.0  (by TensorFlow / Espressif, ESP32-optimised)
 *   • esp32 board support package      (by Espressif, via Boards Manager)
 *
 * Board settings (Tools menu):
 *   Board:           AI Thinker ESP32-CAM
 *   Partition Scheme: Huge APP (3MB No OTA/1MB SPIFFS)
 *   Upload Speed:    115200
 *
 * Wiring: no additional wiring needed – the camera is built into the module.
 *
 * Serial output example:
 *   [INFO] Camera ready.
 *   [INFO] TFLite model loaded. Input: 96x96x1  Output classes: 80
 *   ---- Detection result ----
 *   Object  : cat
 *   Score   : 0.87
 *   --------------------------
 */

// ---------------------------------------------------------------------------
// Includes
// ---------------------------------------------------------------------------
#include "esp_camera.h"
#include "model_data.h"                // generated byte array + label list

// TensorFlow Lite for Microcontrollers headers
#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/schema/schema_generated.h"

// ---------------------------------------------------------------------------
// Camera pin definitions – AI Thinker ESP32-CAM
// ---------------------------------------------------------------------------
#define PWDN_GPIO_NUM     32
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM      0
#define SIOD_GPIO_NUM     26
#define SIOC_GPIO_NUM     27
#define Y9_GPIO_NUM       35
#define Y8_GPIO_NUM       34
#define Y7_GPIO_NUM       39
#define Y6_GPIO_NUM       36
#define Y5_GPIO_NUM       21
#define Y4_GPIO_NUM       19
#define Y3_GPIO_NUM       18
#define Y2_GPIO_NUM        5
#define VSYNC_GPIO_NUM    25
#define HREF_GPIO_NUM     23
#define PCLK_GPIO_NUM     22

// ---------------------------------------------------------------------------
// TFLite configuration
// ---------------------------------------------------------------------------

// Model input dimensions – must match what the model was trained on.
// The bundled person-detection model uses 96×96 greyscale images.
#define MODEL_INPUT_W    96
#define MODEL_INPUT_H    96
#define MODEL_INPUT_CH    1   // 1 = greyscale, 3 = RGB

// Tensor arena size in bytes.  Increase if the interpreter reports
// "AllocateTensors() failed" (kTfLiteError).
constexpr int kTensorArenaSize = 136 * 1024;  // 136 KB

static uint8_t tensor_arena[kTensorArenaSize];

// TFLite objects (file-scope so they persist between loop() calls)
static const tflite::Model*        tfl_model     = nullptr;
static tflite::MicroInterpreter*   interpreter   = nullptr;
static TfLiteTensor*               input_tensor  = nullptr;
static TfLiteTensor*               output_tensor = nullptr;

// ---------------------------------------------------------------------------
// Helper: initialise the OV2640 camera
// ---------------------------------------------------------------------------
static bool initCamera() {
    camera_config_t config;

    config.ledc_channel = LEDC_CHANNEL_0;
    config.ledc_timer   = LEDC_TIMER_0;
    config.pin_d0       = Y2_GPIO_NUM;
    config.pin_d1       = Y3_GPIO_NUM;
    config.pin_d2       = Y4_GPIO_NUM;
    config.pin_d3       = Y5_GPIO_NUM;
    config.pin_d4       = Y6_GPIO_NUM;
    config.pin_d5       = Y7_GPIO_NUM;
    config.pin_d6       = Y8_GPIO_NUM;
    config.pin_d7       = Y9_GPIO_NUM;
    config.pin_xclk     = XCLK_GPIO_NUM;
    config.pin_pclk     = PCLK_GPIO_NUM;
    config.pin_vsync    = VSYNC_GPIO_NUM;
    config.pin_href     = HREF_GPIO_NUM;
    config.pin_sscb_sda = SIOD_GPIO_NUM;
    config.pin_sscb_scl = SIOC_GPIO_NUM;
    config.pin_pwdn     = PWDN_GPIO_NUM;
    config.pin_reset    = RESET_GPIO_NUM;

    config.xclk_freq_hz = 20000000;

    // Capture at the model's native resolution to avoid a software resize step.
    // FRAMESIZE_96X96 = 96×96 pixels.
    config.frame_size   = FRAMESIZE_96X96;

    // GRAYSCALE saves memory and matches the single-channel model input.
    config.pixel_format = PIXFORMAT_GRAYSCALE;
    config.fb_count     = 1;
    config.fb_location  = CAMERA_FB_IN_PSRAM;
    config.grab_mode    = CAMERA_GRAB_WHEN_EMPTY;
    config.jpeg_quality = 12;

    esp_err_t err = esp_camera_init(&config);
    if (err != ESP_OK) {
        Serial.printf("[ERROR] Camera init failed: 0x%x\n", err);
        return false;
    }
    Serial.println("[INFO] Camera ready.");
    return true;
}

// ---------------------------------------------------------------------------
// Helper: initialise TFLite interpreter
// ---------------------------------------------------------------------------
static bool initTFLite() {
    tfl_model = tflite::GetModel(g_model_data);
    if (tfl_model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.printf("[ERROR] Model schema mismatch: expected %d, got %d\n",
                      TFLITE_SCHEMA_VERSION, tfl_model->version());
        return false;
    }

    // AllOpsResolver includes every built-in op; use MicroMutableOpResolver to
    // reduce flash usage once the required ops are known.
    static tflite::AllOpsResolver resolver;

    static tflite::MicroInterpreter static_interpreter(
        tfl_model, resolver, tensor_arena, kTensorArenaSize);
    interpreter = &static_interpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        Serial.println("[ERROR] AllocateTensors() failed – increase kTensorArenaSize.");
        return false;
    }

    input_tensor  = interpreter->input(0);
    output_tensor = interpreter->output(0);

    Serial.printf("[INFO] TFLite model loaded. Input: %dx%dx%d  Output classes: %d\n",
                  input_tensor->dims->data[1],
                  input_tensor->dims->data[2],
                  input_tensor->dims->data[3],
                  output_tensor->dims->data[1]);
    return true;
}

// ---------------------------------------------------------------------------
// Helper: copy greyscale camera frame into the model input tensor
// ---------------------------------------------------------------------------
static void copyFrameToInput(const uint8_t* frame_buf, int width, int height) {
    // The model input is int8 (quantised).  Camera pixels are uint8 [0,255].
    // The standard quantisation maps uint8 → int8 as: int8 = uint8 - 128.
    if (input_tensor->type == kTfLiteInt8) {
        int8_t* dst = input_tensor->data.int8;
        for (int i = 0; i < width * height; ++i) {
            dst[i] = static_cast<int8_t>(static_cast<int>(frame_buf[i]) - 128);
        }
    } else if (input_tensor->type == kTfLiteUInt8) {
        memcpy(input_tensor->data.uint8, frame_buf, width * height);
    } else if (input_tensor->type == kTfLiteFloat32) {
        float* dst = input_tensor->data.f;
        for (int i = 0; i < width * height; ++i) {
            dst[i] = frame_buf[i] / 255.0f;
        }
    }
}

// ---------------------------------------------------------------------------
// Helper: find index of highest output score
// ---------------------------------------------------------------------------
static int argmax(const TfLiteTensor* tensor) {
    int   best_idx   = 0;
    float best_score = -1e9f;

    for (int i = 0; i < tensor->dims->data[1]; ++i) {
        float score = 0.0f;
        if (tensor->type == kTfLiteInt8) {
            score = (tensor->data.int8[i] - tensor->params.zero_point)
                    * tensor->params.scale;
        } else if (tensor->type == kTfLiteUInt8) {
            score = (tensor->data.uint8[i] - tensor->params.zero_point)
                    * tensor->params.scale;
        } else if (tensor->type == kTfLiteFloat32) {
            score = tensor->data.f[i];
        }

        if (score > best_score) {
            best_score = score;
            best_idx   = i;
        }
    }
    return best_idx;
}

// ---------------------------------------------------------------------------
// Helper: dequantise a single output value to float
// ---------------------------------------------------------------------------
static float getScore(const TfLiteTensor* tensor, int idx) {
    if (tensor->type == kTfLiteInt8) {
        return (tensor->data.int8[idx] - tensor->params.zero_point)
               * tensor->params.scale;
    }
    if (tensor->type == kTfLiteUInt8) {
        return (tensor->data.uint8[idx] - tensor->params.zero_point)
               * tensor->params.scale;
    }
    return tensor->data.f[idx];
}

// ---------------------------------------------------------------------------
// Arduino setup()
// ---------------------------------------------------------------------------
void setup() {
    Serial.begin(115200);
    delay(1000);  // allow the Serial monitor to connect
    Serial.println("\n[INFO] ESP32-CAM Object Detection starting…");

    if (!initCamera()) {
        Serial.println("[FATAL] Could not initialise camera. Halting.");
        while (true) { delay(1000); }
    }

    if (!initTFLite()) {
        Serial.println("[FATAL] Could not initialise TFLite. Halting.");
        while (true) { delay(1000); }
    }
}

// ---------------------------------------------------------------------------
// Arduino loop()
// ---------------------------------------------------------------------------
void loop() {
    // 1. Capture a frame
    camera_fb_t* fb = esp_camera_fb_get();
    if (!fb) {
        Serial.println("[ERROR] Failed to capture frame.");
        delay(500);
        return;
    }

    // Validate frame dimensions
    if ((int)fb->width != MODEL_INPUT_W || (int)fb->height != MODEL_INPUT_H) {
        Serial.printf("[WARN] Unexpected frame size: %dx%d (expected %dx%d)\n",
                      fb->width, fb->height, MODEL_INPUT_W, MODEL_INPUT_H);
        esp_camera_fb_return(fb);
        delay(500);
        return;
    }

    // 2. Pre-process: copy frame pixels into the TFLite input tensor
    copyFrameToInput(fb->buf, fb->width, fb->height);
    esp_camera_fb_return(fb);  // return frame buffer as soon as possible

    // 3. Run inference
    TfLiteStatus invoke_status = interpreter->Invoke();
    if (invoke_status != kTfLiteOk) {
        Serial.println("[ERROR] Invoke() failed.");
        delay(500);
        return;
    }

    // 4. Read results and print the top prediction to Serial
    int   best_idx   = argmax(output_tensor);
    float best_score = getScore(output_tensor, best_idx);

    const char* label = (best_idx < g_num_labels) ? g_labels[best_idx] : "unknown";

    Serial.println("---- Detection result ----");
    Serial.printf("Object  : %s\n", label);
    Serial.printf("Score   : %.2f\n", best_score);
    Serial.println("--------------------------");

    // 5. Wait before next capture (adjust as needed)
    delay(2000);
}
